// AppFlow
export const UI_BLOCK = 'UI_BLOCK'

//Auth
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'

export const FETCH_PODS_REQUEST = 'FETCH_PODS_REQUEST'
export const FETCH_PODS_SUCCESS = 'FETCH_PODS_SUCCESS'
export const FETCH_PODS_ERROR = 'FETCH_PODS_ERROR'
