// AppFlow
export const UI_BLOCK = 'UI_BLOCK'

//Auth
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD'
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR'
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'

export const FETCH_PODS_REQUEST = 'FETCH_PODS_REQUEST'
export const FETCH_PODS_SUCCESS = 'FETCH_PODS_SUCCESS'
export const FETCH_PODS_ERROR = 'FETCH_PODS_ERROR'

export const FETCH_ACTIVE_WORK_ORDERS_REQUEST = 'FETCH_ACTIVE_WORK_ORDERS_REQUEST'
export const FETCH_ACTIVE_WORK_ORDERS_SUCCESS = 'FETCH_ACTIVE_WORK_ORDERS_SUCCESS'
export const FETCH_ACTIVE_WORK_ORDERS_ERROR = 'FETCH_ACTIVE_WORK_ORDERS_ERROR'

export const FETCH_AVAILABLE_WORK_ORDERS_REQUEST = 'FETCH_AVAILABLE_WORK_ORDERS_REQUEST'
export const FETCH_AVAILABLE_WORK_ORDERS_SUCCESS = 'FETCH_AVAILABLE_WORK_ORDERS_SUCCESS'
export const FETCH_AVAILABLE_WORK_ORDERS_ERROR = 'FETCH_AVAILABLE_WORK_ORDERS_ERROR'

export const FETCH_WAITING_FOR_REVIEW_WORK_ORDERS_REQUEST = 'FETCH_WAITING_FOR_REVIEW_WORK_ORDERS_REQUEST'
export const FETCH_WAITING_FOR_REVIEW_WORK_ORDERS_SUCCESS = 'FETCH_WAITING_FOR_REVIEW_WORK_ORDERS_SUCCESS'
export const FETCH_WAITING_FOR_REVIEW_WORK_ORDERS_ERROR = 'FETCH_WAITING_FOR_REVIEW_WORK_ORDERS_ERROR'

export const FETCH_ALL_SKILLS_REQUEST = 'FETCH_ALL_SKILLS_REQUEST'
export const FETCH_ALL_SKILLS_SUCCESS = 'FETCH_ALL_SKILLS_SUCCESS'
export const FETCH_ALL_SKILLS_ERROR = 'FETCH_ALL_SKILLS_ERROR'

export const FETCH_SKILL_BY_ID_REQUEST = 'FETCH_SKILL_BY_ID_REQUEST'
export const FETCH_SKILL_BY_ID_SUCCESS = 'FETCH_SKILL_BY_ID_SUCCESS'
export const FETCH_SKILL_BY_ID_ERROR = 'FETCH_SKILL_BY_ID_ERROR'

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_ERROR = 'UPDATE_USER_PROFILE_ERROR'

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR'

export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS'
export const UPDATE_TASK_ERROR = 'UPDATE_TASK_ERROR'
