const ENUMS = {
  ROLE: {
    USER: 'USER',
    CONSULTANT: 'CONSULTANT',
  },

  PHONE: 'PHONE',
  EMAIL: 'EMAIL',
  USER_NAME: 'USERNAME',

  EMAIL_SIGNUP_TOKEN: 'EMAIL_SIGNUP_TOKEN',
  PHONE_SIGNUP_TOKEN: 'PHONE_SIGNUP_TOKEN',

  EMAIL_UPDATE_TOKEN: 'EMAIL_UPDATE_TOKEN',
  PHONE_UPDATE_TOKEN: 'PHONE_UPDATE_TOKEN',

  PROFILE_PHONE_UPDATE_TOKEN: 'PROFILE_PHONE_UPDATE_TOKEN',
  PROFILE_EMAIL_UPDATE_TOKEN: 'PROFILE_EMAIL_UPDATE_TOKEN',

  CERTIFICATE_DOCUMENT: 'CERTIFICATE_DOCUMENT',
  ID_DOCUMENT: 'ID_DOCUMENT',

  USER_PROFILE:"USER_PROFILE",
  CONTENT_TIMELINE_COMMENT:"CONTENT_TIMELINE_COMMENT",
  CONTENT_TIMELINE_POST:"CONTENT_TIMELINE_POST",
};

export default ENUMS;
